CRM/Entities/InfoEmpresa.cs
using System;
using System.Collections.Generic;

namespace CRM.Entities;

public partial class InfoEmpresa
{
    public int IdInfoEmpresa { get; set; }

    public string? Nombre { get; set; }

    public string? Correo { get; set; }

    public string? Telefono { get; set; }

    public string? Actividad { get; set; }

    public int? IdTipoIdentificacion { get; set; }

    public string? Identificacion { get; set; }

    public virtual TipoIdentificacion? IdTipoIdentificacionNavigation { get; set; }
}

CRM/ViewModels/InfoEmpresaViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace CRM.ViewModels
{
    public class InfoEmpresaViewModel
    {
        public int IdInfoEmpresa { get; set; }

        public string? Nombre { get; set; }

        public string? Correo { get; set; }

        public string? Telefono { get; set; }

        public string? Actividad { get; set; }

        public int? IdTipoIdentificacion { get; set; }

        public string? Identificacion { get; set; }
    }
}

CRM/Controllers/InfoEmpresaController.cs
using CRM.APIModels;
using CRM.Helpers.Interfaces;
using CRM.ViewModels;
using Entities.Entities;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Newtonsoft.Json;

namespace CRM.Controllers
{
    public class InfoEmpresaController : Controller
    {
        IInfoEmpresaHelper _infoEmpresaHelper;
        private readonly IHttpContextAccessor _HttpCA;

        public InfoEmpresaController(IInfoEmpresaHelper infoEmpresaHelper, IHttpContextAccessor httpContextAccessor)
        {
            _infoEmpresaHelper = infoEmpresaHelper;
            _HttpCA = httpContextAccessor;
        }

        public IActionResult Index()
        {
            try
            {
                var usuarioEnSesion = _HttpCA.HttpContext?.Session.GetString("UsuarioEnSesion");

                if (usuarioEnSesion == null)
                {
                    TempData["LoginError"] = "Tiempo de sesión finalizó";
                    return Redirect("/Account/Login");
                }

                ViewBag.UsuarioEnSesion = usuarioEnSesion;
                var listadoEmpresas = _infoEmpresaHelper.GetEmpresas();

                if (!listadoEmpresas.Any())
                {
                    ViewData["NoDataList"] = "No existen datos para mostrar";
                    return View(new List<InfoEmpresaViewModel>());
                }

                return View(listadoEmpresas);
            }
            catch (Exception ex)
            {
                ViewData["ErrorList"] = $"Ocurrió un error al listar la información: {ex.Message}";
                return View(new List<InfoEmpresaViewModel>());
            }
        }

        public IActionResult Agregar()
        {
            var usuarioEnSesion = _HttpCA.HttpContext?.Session.GetString("UsuarioEnSesion");

            if (usuarioEnSesion == null)
            {
                TempData["LoginError"] = "Tiempo de sesión finalizó";
                return Redirect("/Account/Login");
            }

            ViewBag.UsuarioEnSesion = usuarioEnSesion;
            ViewData["TiposIdentificacion"] = GetTiposIdentificacion();
            return View();
        }

        public IActionResult Editar(int id)
        {
            try
            {
                var usuarioEnSesion = _HttpCA.HttpContext?.Session.GetString("UsuarioEnSesion");

                if (usuarioEnSesion == null)
                {
                    TempData["LoginError"] = "Tiempo de sesión finalizó";
                    return Redirect("/Account/Login");
                }

                ViewBag.UsuarioEnSesion = usuarioEnSesion;
                var empresa = _infoEmpresaHelper.GetEmpresaById(id);

                if (empresa == null)
                {
                    ViewData["NoItemById"] = "No se ha encontrado la empresa";
                    return View(new InfoEmpresaViewModel());
                }

                ViewData["TiposIdentificacion"] = GetTiposIdentificacion();
                return View(empresa);
            }
            catch (Exception ex)
            {
                ViewData["ErrorItemById"] = $"Ocurrió un error al obtener la empresa: {ex.Message}";
                return View(new InfoEmpresaViewModel());
            }
        }

        [HttpPost]
        public IActionResult AgregarEmpresa(InfoEmpresaViewModel model)
        {
            var usuarioEnSesion = _HttpCA.HttpContext?.Session.GetString("UsuarioEnSesion");

            if (usuarioEnSesion == null)
            {
                TempData["LoginError"] = "Tiempo de sesión finalizó";
                return Redirect("/Account/Login");
            }

            if (ModelState.IsValid)
            {
                _infoEmpresaHelper.AddEmpresa(model);
                TempData["NewEmpresa"] = model.Nombre;
                return Redirect("/InfoEmpresa/Index");
            }
            else
            {
                return Redirect("/InfoEmpresa/Index");
            }
        }


        [HttpPost]
        public IActionResult EditarEmpresa(InfoEmpresaViewModel model)
        {
            var usuarioEnSesion = _HttpCA.HttpContext?.Session.GetString("UsuarioEnSesion");

            if (usuarioEnSesion == null)
            {
                TempData["LoginError"] = "Tiempo de sesión finalizó";
                return Redirect("/Account/Login");
            }

            if (ModelState.IsValid)
            {
                _infoEmpresaHelper.UpdateEmpresa(model);
                return Redirect("/InfoEmpresa/Index");
            }
            else
            {
                return Redirect("/InfoEmpresa/Index");
            }
        }


        [HttpPost]
        public IActionResult CambiarEstadoEmpresa(int id, bool inactivar)
        {
            var usuarioEnSesion = _HttpCA.HttpContext?.Session.GetString("UsuarioEnSesion");

            if (usuarioEnSesion == null)
            {
                TempData["LoginError"] = "Tiempo de sesión finalizó";
                return Redirect("/Account/Login");
            }

            var empresa = _infoEmpresaHelper.GetEmpresaById(id);

            if (empresa != null)
            {
                _infoEmpresaHelper.UpdateEmpresa(empresa);
                return Redirect("/InfoEmpresa/Index");
            }
            else
            {
                return Redirect("/InfoEmpresa/Index");
            }
        }


        #region [Métodos]

        public List<TipoIdentificacion> GetTiposIdentificacion()
        {
            var tiposIdSesion = _HttpCA.HttpContext?.Session.GetString("TiposIdentificacion");

            if (tiposIdSesion == null)
            {
                var listadoTiposIdentificacion = _infoEmpresaHelper.GetTiposIdentificacion();

                if (listadoTiposIdentificacion != null)
                {
                    _HttpCA.HttpContext?.Session.SetString("TiposIdentificacion", JsonConvert.SerializeObject(listadoTiposIdentificacion));
                    return listadoTiposIdentificacion;
                }
                else
                {
                    return new List<TipoIdentificacion>();
                }
            }
            else
            {
                return JsonConvert.DeserializeObject<List<TipoIdentificacion>>(tiposIdSesion);
            }
        }

        #endregion
    }
}

CRM/Views/InfoEmpresa/Agregar.cshtml
@using Entities.Entities
@using CRM.ViewModels;
@model CRM.ViewModels.InfoEmpresaViewModel;

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewData["Title"] = "Agregar Empresa";
    string[] items = new string[] { "Empresas", "Agregar Empresa" };
}

@{
    var op = ViewData["TiposIdentificacion"];
    IEnumerable<TipoIdentificacion> tiOptions = op as IEnumerable<TipoIdentificacion>;
}

<div class="pt-16 lg:pl-64 pl-0 bg-white dark:bg-gray-900">
    <div class="p-4 pt-40 sm:ml-64">
        <div class="p-1">
            <nav class="flex" aria-label="Breadcrumb">
                <ol class="inline-flex items-center space-x-1 md:space-x-2 rtl:space-x-reverse">
                    @HtmlElement.TailwindBreadCrumb(Html, items)
                </ol>
            </nav>
            <br />
            <div class="p-1">
                <div class="mt-3 grid grid-cols-12 mb-3">
                    <div class="col-span-12 lg:col-span-6">
                        <div class="bg-gray-100 dark:bg-gray-800 p-6 rounded-lg shadow-lg">
                            <h5 class="text-xl font-bold mb-4 dark:text-white">Agregar Nueva Empresa</h5>
                            <hr class="h-px my-2 bg-gray-400 border-0 dark:bg-gray-100">
                            <form action="AgregarEmpresa" method="POST" class="p-4 md:p-5">
                                <div class="grid gap-4 mb-4 grid-cols-1 md:grid-cols-2">
                                    <div class="col-span-1">
                                        <div class="block mb-2 text-md font-medium text-gray-900 dark:text-white">
                                            Nombre de la Empresa
                                        </div>
                                        @Html.TextBoxFor(model => model.Nombre, new { @class = "bg-gray-50 border border-gray-300 text-gray-900 text-md rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-800 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500", placeholder = "Nombre de la Empresa", required = "required" })
                                        @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-red-600 dark:text-red-500" })
                                        <span asp-validation-for="Nombre" class="text-red-600"></span>
                                    </div>

                                    <div class="col-span-1">
                                        <div class="block mb-2 text-md font-medium text-gray-900 dark:text-white">
                                            Correo Electrónico
                                        </div>
                                        @Html.TextBoxFor(model => model.Correo, new { @class = "bg-gray-50 border border-gray-300 text-gray-900 text-md rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-800 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500", placeholder = "Correo de la Empresa", required = "required" })
                                        <span asp-validation-for="Correo" class="text-red-600"></span>
                                    </div>
                                </div>

                                <div class="grid gap-4 mb-4 grid-cols-1 md:grid-cols-4">
                                    <div class="col-span-1">
                                        <div class="block mb-2 text-md font-medium text-gray-900 dark:text-white">
                                            Teléfono
                                        </div>
                                        @Html.TextBoxFor(model => model.Telefono, new { @class = "bg-gray-50 border border-gray-300 text-gray-900 text-md rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-800 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500", placeholder = "Teléfono de la Empresa", required = "required" })
                                        <span asp-validation-for="Telefono" class="text-red-600"></span>
                                    </div>

                                    <div class="col-span-1">
                                        <div class="block mb-2 text-md font-medium text-gray-900 dark:text-white">
                                            Tipo de Identificación
                                        </div>
                                        @if (tiOptions != null)
                                        {
                                            @Html.DropDownListFor(
                                                     model => model.IdTipoIdentificacion,
                                                     new SelectList(tiOptions, "IdTipoIdentificacion", "Nombre"),
                                                     "Seleccione un Tipo",
                                                     new { @class = "bg-gray-50 border border-gray-300 text-gray-900 text-md rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-800 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500", required = "required" }
                                                     )
                                        }
                                        else
                                        {
                                            <span class="text-red-600">Debe seleccionar un tipo de identificación</span>
                                        }
                                        <span asp-validation-for="IdTipoIdentificacion" class="text-red-600"></span>
                                    </div>

                                    <div class="col-span-1">
                                        <div class="block mb-2 text-md font-medium text-gray-900 dark:text-white">
                                            Identificación
                                        </div>
                                        @Html.TextBoxFor(model => model.Identificacion, new { @class = "bg-gray-50 border border-gray-300 text-gray-900 text-md rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-800 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500", placeholder = "Identificación de la Empresa", required = "required" })
                                        <span asp-validation-for="Identificacion" class="text-red-600"></span>
                                    </div>

                                    <div class="col-span-1">
                                        <div class="block mb-2 text-md font-medium text-gray-900 dark:text-white">
                                            Actividad
                                        </div>
                                        @Html.TextBoxFor(model => model.Actividad, new { @class = "bg-gray-50 border border-gray-300 text-gray-900 text-md rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-800 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500", placeholder = "Actividad de la Empresa", required = "required" })
                                        <span asp-validation-for="Actividad" class="text-red-600"></span>
                                    </div>
                                </div>

                                <div class="grid gap-4 mb-4 grid-cols-1 md:grid-cols-1">
                                    <div class="mt-4">
                                        @HtmlElement.Button(Html, "green", "Registrar", "", "submit", "fa-solid fa-plus", "", "")
                                        @HtmlElement.ActionLink(Html, "gray", "Regresar al listado", "Index", "InfoEmpresa", "fa-solid fa-undo", "")
                                    </div>
                                </div>
                            </form>

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

CRM/Views/InfoEmpresa/Editar.cshtml
@using Entities.Entities
@using CRM.ViewModels;
@model CRM.ViewModels.InfoEmpresaViewModel;

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewData["Title"] = "Editar Empresa";
    string[] items = new string[] { "Empresas", "Editar Empresa" };
}

@{
    var op = ViewData["TiposIdentificacion"];
    IEnumerable<TipoIdentificacion> tiOptions = op as IEnumerable<TipoIdentificacion>;
}

<div class="pt-16 lg:pl-64 pl-0 bg-white dark:bg-gray-900">
    <div class="p-4 pt-40 sm:ml-64">
        <div class="p-1">
            <nav class="flex" aria-label="Breadcrumb">
                <ol class="inline-flex items-center space-x-1 md:space-x-2 rtl:space-x-reverse">
                    @HtmlElement.TailwindBreadCrumb(Html, items)
                </ol>
            </nav>
            <br />
            <div class="p-1">
                <div class="mt-3 grid grid-cols-12 mb-3">
                    <div class="col-span-12 lg:col-span-6">
                        <div class="bg-gray-100 dark:bg-gray-800 p-6 rounded-lg shadow-lg">
                            <h5 class="text-xl font-bold mb-4 dark:text-white">Editar Empresa</h5>
                            <hr class="h-px my-2 bg-gray-400 border-0 dark:bg-gray-100">
                            @if (ViewData["NoItemById"] != null)
                            {
                                @HtmlElement.TailwindAlert(Html, "Advertencia", ViewData["NoItemById"].ToString(), "yellow", "fa-solid fa fa-exclamation-triangle", "")
                            }
                            @if (Model.IdInfoEmpresa != 0)
                            {
                                <form asp-action="EditarEmpresa" class="p-4 md:p-5">
                                    <div class="grid gap-4 mb-4 grid-cols-1 md:grid-cols-2">
                                        <div hidden class="col-span-1">
                                            <div class="block mb-2 text-md font-medium text-gray-900 dark:text-white">
                                                IdEmpresa
                                            </div>
                                            @Html.TextBoxFor(model => model.IdInfoEmpresa, new { @class = "bg-gray-50 border border-gray-300 text-gray-900 text-md rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-800 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" })
                                        </div>

                                        <div class="col-span-1">
                                            <div class="block mb-2 text-md font-medium text-gray-900 dark:text-white">
                                                Nombre
                                            </div>
                                            @Html.TextBoxFor(model => model.Nombre, new { @class = "bg-gray-50 border border-gray-300 text-gray-900 text-md rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-800 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500", placeholder = "Nombre de la Empresa", required = "required" })
                                            @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-red-600 dark:text-red-500" })
                                            <span asp-validation-for="Nombre" class="text-red-600"></span>
                                        </div>

                                        <div class="col-span-1">
                                            <div class="block mb-2 text-md font-medium text-gray-900 dark:text-white">
                                                Correo
                                            </div>
                                            @Html.TextBoxFor(model => model.Correo, new { @class = "bg-gray-50 border border-gray-300 text-gray-900 text-md rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-800 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500", placeholder = "Correo de la Empresa", required = "required" })
                                            <span asp-validation-for="Correo" class="text-red-600"></span>
                                        </div>
                                    </div>

                                    <div class="grid gap-4 mb-4 grid-cols-1 md:grid-cols-4">
                                        <div class="col-span-1">
                                            <div class="block mb-2 text-md font-medium text-gray-900 dark:text-white">
                                                Teléfono
                                            </div>
                                            @Html.TextBoxFor(model => model.Telefono, new { @class = "bg-gray-50 border border-gray-300 text-gray-900 text-md rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-800 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500", placeholder = "Teléfono de la Empresa", required = "required" })
                                            <span asp-validation-for="Telefono" class="text-red-600"></span>
                                        </div>

                                        <div class="col-span-1">
                                            <div class="block mb-2 text-md font-medium text-gray-900 dark:text-white">
                                                Tipo Identificación
                                            </div>
                                            @if (tiOptions != null)
                                            {
                                                @Html.DropDownListFor(
                                                         model => model.IdTipoIdentificacion,
                                                         new SelectList(tiOptions, "IdTipoIdentificacion", "Nombre"),
                                                         "Seleccione un Tipo",
                                                         new { @class = "bg-gray-50 border border-gray-300 text-gray-900 text-md rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-800 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500", required = "required" }
                                                         )
                                            }
                                            else
                                            {
                                                <span class="text-red-600">No hay datos...</span>
                                            }
                                            <span asp-validation-for="IdTipoIdentificacion" class="text-red-600"></span>
                                        </div>

                                        <div class="col-span-1">
                                            <div class="block mb-2 text-md font-medium text-gray-900 dark:text-white">
                                                Identificación
                                            </div>
                                            @Html.TextBoxFor(model => model.Identificacion, new { @class = "bg-gray-50 border border-gray-300 text-gray-900 text-md rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-800 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500", placeholder = "Identificación de la Empresa", required = "required" })
                                            <span asp-validation-for="Identificacion" class="text-red-600"></span>
                                        </div>

                                        <div class="col-span-1">
                                            <div class="block mb-2 text-md font-medium text-gray-900 dark:text-white">
                                                Actividad
                                            </div>
                                            @Html.TextBoxFor(model => model.Actividad, new { @class = "bg-gray-50 border border-gray-300 text-gray-900 text-md rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-800 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500", placeholder = "Actividad de la Empresa", required = "required" })
                                            <span asp-validation-for="Actividad" class="text-red-600"></span>
                                        </div>
                                    </div>

                                    <div class="grid gap-4 mb-4 grid-cols-1 md:grid-cols-1">
                                        <div class="mt-4">
                                            @HtmlElement.Button(Html, "blue", "Actualizar", "", "submit", "fa-solid fa-pencil", "", "")
                                            @HtmlElement.ActionLink(Html, "gray", "Regresar al listado", "Index", "InfoEmpresa", "fa-solid fa-undo", "")
                                        </div>
                                    </div>
                                </form>
                            }
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

CRM/Views/InfoEmpresa/Index.cshtml
@model IEnumerable<InfoEmpresaViewModel>

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewData["Title"] = "Administrar Información de Empresas";
    string[] items = new string[] { "Empresas", "Adm. Empresas" };
}

<div class="pt-16 lg:pl-64 pl-0 bg-white dark:bg-gray-900">
    <div class="p-4 pt-40 sm:ml-64">
        <div class="p-1">
            <nav class="flex" aria-label="Breadcrumb">
                <ol class="inline-flex items-center space-x-1 md:space-x-2 rtl:space-x-reverse">
                    @HtmlElement.TailwindBreadCrumb(Html, items)
                </ol>
            </nav>
            <br />
            <div class="p-1">
                <h4 class="text-2xl font-bold dark:text-white">Información de Empresas</h4>
                <div class="mt-4 grid grid-cols-12 mb-3">
                    <div class="mt-2 mb-2 flex items-center justify-between flex-column flex-wrap md:flex-row space-y-4 md:space-y-0 pb-4 bg-white dark:bg-gray-900">
                        <div class="relative">
                            @HtmlElement.ActionLink(Html, "purple", "Agregar Empresa", "Agregar", "InfoEmpresa", "fa-solid fa-building", "btnAddEmpresa")
                        </div>
                    </div>
                    @if (TempData["SuccessAction"] != null)
                    {
                        @HtmlElement.TailwindAlert(Html, "Información", TempData["SuccessAction"].ToString(), "green", "fa-solid fa fa-check", "")
                    }

                    @if (TempData["ErrorAction"] != null)
                    {
                        @HtmlElement.TailwindAlert(Html, "Error", TempData["ErrorAction"].ToString(), "red", "fa-solid fa fa-times", "")
                    }

                    @if (ViewData["NoDataList"] != null)
                    {
                        @HtmlElement.TailwindAlert(Html, "Advertencia", ViewData["NoDataList"].ToString(), "yellow", "fa-solid fa fa-exclamation-triangle", "")
                    }

                    @if (ViewData["ErrorList"] != null)
                    {
                        @HtmlElement.TailwindAlert(Html, "Ocurrió un error", ViewData["ErrorList"].ToString(), "red", "fa-solid fa fa-times-circle", "")
                    }

                    @if (Model.Any())
                    {
                        <div class="relative overflow-x-auto shadow-md sm:rounded-lg">
                            <div style="overflow:auto; max-height:30rem">
                                <!-- Tabla de Empresas -->
                                <table class="w-full text-sm text-left rtl:text-right text-gray-500 dark:text-gray-400">
                                    <thead class="text-xs text-gray-700 uppercase bg-gray-200 dark:bg-gray-700 dark:text-gray-400">
                                        <tr>
                                            <th hidden scope="col" class="px-6 py-3">IdEmpresa</th>
                                            <th scope="col" class="px-6 py-3">Nombre</th>
                                            <th scope="col" class="px-6 py-3">Identificación</th>
                                            <th scope="col" class="px-6 py-3">Correo / Teléfonos</th>
                                            <th scope="col" class="px-6 py-3">Actividad</th>
                                            <th scope="col" class="px-6 py-3">Acciones</th>
                                        </tr>
                                    </thead>
                                    <tbody class="bg-gray-50 dark:bg-gray-800">
                                        @foreach (var item in Model)
                                        {
                                            <tr>
                                                <td hidden class="px-6 py-4">@item.IdInfoEmpresa</td>
                                                <td class="px-6 py-4">@item.Nombre</td>
                                                <td class="px-6 py-4">@item.Identificacion</td>
                                                <td class="px-6 py-4">
                                                    <div class="ps-3">
                                                        @{
                                                            var telefonoFormat = @item.Telefono != null ? @item.Telefono.Substring(0, 4) + "-" + @item.Telefono.Substring(4, 4) : "N/A";
                                                        }
                                                        <div id="telefono_@item.IdInfoEmpresa" class="m-2">@HtmlElement.TailwindBadge(Html, "blue", "fa-solid fa-phone", telefonoFormat, "")</div>
                                                        <div id="correo_@item.IdInfoEmpresa" class="m-2">@HtmlElement.TailwindBadge(Html, "gray", "fa-solid fa-envelope", @item.Correo ?? "N/A", "")</div>
                                                    </div>
                                                </td>
                                                <td class="px-6 py-4">@item.Actividad</td>
                                                <td class="px-6 py-4">
                                                    @HtmlElement.TailwindTableButton(Html, "blue", "", "fa-solid fa-pencil", "", "btn", "Editar Empresa", $"/InfoEmpresa/Editar/{item.IdInfoEmpresa}")
                                                </td>
                                            </tr>
                                        }
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    }


                </div>

            </div>
        </div>
    </div>
</div>