CRM/Entities/Movimiento.cs
using System;
using System.Collections.Generic;

namespace CRM.Entities;

public partial class Movimiento
{
    public int IdMovimiento { get; set; }

    public int? IdTipoMovimiento { get; set; }

    public int? IdEstadoMovimiento { get; set; }

    public decimal? Monto { get; set; }

    public DateTime? FechaCreacion { get; set; }

    public string? IdUsuarioCreacion { get; set; }

    public DateTime? FechaModificacion { get; set; }

    public string? IdUsuarioModificacion { get; set; }

    public string? Comentario { get; set; }

    public byte[]? Imagen { get; set; }

    public string? TipoImagen { get; set; }

    public virtual TipoEstadoMovimiento? IdEstadoMovimientoNavigation { get; set; }

    public virtual TipoMovimiento? IdTipoMovimientoNavigation { get; set; }
}

CRM/ViewModels/MovimientosViewModel.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
namespace CRM.ViewModels
{
    public class MovimientosViewModel
    {
        public int IdMovimiento { get; set; }

        public int? IdTipoMovimiento { get; set; }

        public int? IdEstadoMovimiento { get; set; }

        [Required]
        public decimal? Monto { get; set; }

        public DateTime? FechaCreacion { get; set; }

        public string? IdUsuarioCreacion { get; set; }

        public DateTime? FechaModificacion { get; set; }

        public string? IdUsuarioModificacion { get; set; }

        [Required]
        public string? Comentario { get; set; }

        public byte[]? Imagen { get; set; }
    }
}

CRM/Controllers/MovimientoController.cs
using CRM.APIModels;
using CRM.Helpers.Interfaces;
using CRM.ViewModels;
using Entities.Entities;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;

namespace CRM.Controllers
{
    public class MovimientoController : Controller
    {

        IMovimientosHelper MovimientosHelper;
        private readonly IHttpContextAccessor _HttpCA;

        public MovimientoController(IMovimientosHelper movimientosHelper, IHttpContextAccessor httpCA)
        {
            MovimientosHelper = movimientosHelper;
            _HttpCA = httpCA;
        }

        // GET: MovimientoController
        public IActionResult IndexSal()
        {
            try
            {
                var usuarioEnSesion = _HttpCA.HttpContext?.Session.GetString("UsuarioEnSesion");

                if (usuarioEnSesion == null)
                {
                    TempData["LoginError"] = "Tiempo de sesión finalizó";
                    return Redirect("/Account/Login");
                }
                else
                {
                    ViewBag.UsuarioEnSesion = usuarioEnSesion;
                    var listadoMovimiento = MovimientosHelper.GetMovimientos();

                    if (listadoMovimiento.Count == 0)
                    {
                        ViewData["NoDataList"] = "No existen datos para mostrar";
                        return View(new List<MovimientosViewModel>());
                    }
                    else
                    {
                        return View(listadoMovimiento);
                    }
                }
            }
            catch (Exception ex)
            {
                ViewData["ErrorList"] = $"Ocurrió un error al listar la información: {ex}";
                return View(new List<MovimientosViewModel>());

            }
        }

        public IActionResult IndexEnt()
        {
            try
            {
                var usuarioEnSesion = _HttpCA.HttpContext?.Session.GetString("UsuarioEnSesion");

                if (usuarioEnSesion == null)
                {
                    TempData["LoginError"] = "Tiempo de sesión finalizó";
                    return Redirect("/Account/Login");
                }
                else
                {
                    ViewBag.UsuarioEnSesion = usuarioEnSesion;
                    var listadoMovimiento = MovimientosHelper.GetMovimientos();

                    if (listadoMovimiento.Count == 0)
                    {
                        ViewData["NoDataList"] = "No existen datos para mostrar";
                        return View(new List<MovimientosViewModel>());
                    }
                    else
                    {
                        return View(listadoMovimiento);
                    }
                }
            }
            catch (Exception ex)
            {
                ViewData["ErrorList"] = $"Ocurrió un error al listar la información: {ex}";
                return View(new List<MovimientosViewModel>());

            }
        }

        public IActionResult AgregarEnt()
        {
            var usuarioEnSesion = _HttpCA.HttpContext?.Session.GetString("UsuarioEnSesion");

            if (usuarioEnSesion == null)
            {
                TempData["LoginError"] = "Tiempo de sesión finalizó";
                return Redirect("/Account/Login");
            }
            else
            {
                ViewBag.UsuarioEnSesion = usuarioEnSesion;
                return View();
            }


        }

        public IActionResult AgregarSal()
        {
            var usuarioEnSesion = _HttpCA.HttpContext?.Session.GetString("UsuarioEnSesion");

            if (usuarioEnSesion == null)
            {
                TempData["LoginError"] = "Tiempo de sesión finalizó";
                return Redirect("/Account/Login");
            }
            else
            {
                ViewBag.UsuarioEnSesion = usuarioEnSesion;
                return View();
            }


        }

        public IActionResult EditarEnt(int id)
        {
            try
            {
                var usuarioEnSesion = _HttpCA.HttpContext?.Session.GetString("UsuarioEnSesion");

                if (usuarioEnSesion == null)
                {
                    TempData["LoginError"] = "Tiempo de sesión finalizó";
                    return Redirect("/Account/Login");
                }
                else
                {
                    ViewBag.UsuarioEnSesion = usuarioEnSesion;
                    var item = MovimientosHelper.GetMovimientoByID(id);
                    if (item == null)
                    {
                        ViewData["NoItemById"] = "No se ha encontrado el movimiento";
                        return View(new MovimientosViewModel());
                    }
                    else
                    {
                        var tiposEstado = new List<TipoEstadoMovimiento>()
                        {
                            new TipoEstadoMovimiento { IdEstadoMovimiento = 1, Nombre = "Pendiente" },
                            new TipoEstadoMovimiento { IdEstadoMovimiento = 2, Nombre = "Pagado" },
                            new TipoEstadoMovimiento { IdEstadoMovimiento = 3, Nombre = "Anulado" }
                        };
                        ViewData["TiposEstado"] = tiposEstado;
                        return View(item);
                    }
                }



            }
            catch (Exception ex)
            {
                ViewData["ErrorItemById"] = $"Ocurrió un error al obtener el item: {ex}";
                return View(new MovimientosViewModel());

            }
        }

        public IActionResult EditarSal(int id)
        {
            try
            {
                var usuarioEnSesion = _HttpCA.HttpContext?.Session.GetString("UsuarioEnSesion");

                if (usuarioEnSesion == null)
                {
                    TempData["LoginError"] = "Tiempo de sesión finalizó";
                    return Redirect("/Account/Login");
                }
                else
                {
                    ViewBag.UsuarioEnSesion = usuarioEnSesion;
                    var item = MovimientosHelper.GetMovimientoByID(id);
                    if (item == null)
                    {
                        ViewData["NoItemById"] = "No se ha encontrado el movimiento";
                        return View(new MovimientosViewModel());
                    }
                    else
                    {
                        var tiposEstado = new List<TipoEstadoMovimiento>()
                        {
                            new TipoEstadoMovimiento { IdEstadoMovimiento = 1, Nombre = "Pendiente" },
                            new TipoEstadoMovimiento { IdEstadoMovimiento = 2, Nombre = "Pagado" },
                            new TipoEstadoMovimiento { IdEstadoMovimiento = 3, Nombre = "Anulado" }
                        };
                        ViewData["TiposEstado"] = tiposEstado;
                        return View(item);
                    }
                }



            }
            catch (Exception ex)
            {
                ViewData["ErrorItemById"] = $"Ocurrió un error al obtener el item: {ex}";
                return View(new MovimientosViewModel());

            }
        }

        #region [Métodos]

        public List<TipoEstadoMovimiento> GetTiposIdentificacion()
        {
            var tiposIdSesion = _HttpCA.HttpContext?.Session.GetString("TiposIdentificacion");

            if (tiposIdSesion == null)
            {
                var listadoClientesTiposId = MovimientosHelper.GetTipoEstado();

                if (listadoClientesTiposId != null)
                {
                    _HttpCA.HttpContext?.Session.SetString("TipoEstadoMovimiento", JsonConvert.SerializeObject(listadoClientesTiposId));
                    return listadoClientesTiposId;
                }
                else
                {
                    return new List<TipoEstadoMovimiento>();
                }
            }
            else
            {
                return JsonConvert.DeserializeObject<List<TipoEstadoMovimiento>>(tiposIdSesion);
            }

        }

        [HttpPost]
        public IActionResult AgregarMovSal(MovimientosViewModel model)
        {
            var usuarioEnSesion = _HttpCA.HttpContext?.Session.GetString("UsuarioEnSesion");

            if (usuarioEnSesion == null)
            {
                TempData["LoginError"] = "Tiempo de sesión finalizó";
                return Redirect("/Account/Login");
            }
            else
            {
                var usuarioModel = JsonConvert.DeserializeObject<BeforeLoginModel>(usuarioEnSesion);


                if (ModelState.IsValid)
                {
                    model.Imagen = null;
                    model.IdEstadoMovimiento = 1;
                    model.IdTipoMovimiento = 2;
                    model.IdUsuarioCreacion = usuarioModel.Id;

                    _ = MovimientosHelper.AddSalEnt(model);
                    return Redirect("/Movimiento/IndexSal");
                }
                else
                {
                    return Redirect("/Movimiento/IndexSal");

                }
            }
        }

        [HttpPost]
        public IActionResult AgregarMovEnt(MovimientosViewModel model)
        {
            var usuarioEnSesion = _HttpCA.HttpContext?.Session.GetString("UsuarioEnSesion");

            if (usuarioEnSesion == null)
            {
                TempData["LoginError"] = "Tiempo de sesión finalizó";
                return Redirect("/Account/Login");
            }
            else
            {
                var usuarioModel = JsonConvert.DeserializeObject<BeforeLoginModel>(usuarioEnSesion);


                if (ModelState.IsValid)
                {
                    model.Imagen = null;
                    model.IdEstadoMovimiento = 1;

CRM/Views/Movimiento/AgregarEnt.cshtml
@using Entities.Entities
@model CRM.ViewModels.MovimientosViewModel;

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewData["Title"] = "Agregar Movimiento";
    string[] items = new string[] { "Movimientos", "Agregar Entrada de Dinero" };
}

@{

}

<div class="pt-16 lg:pl-64 pl-0 bg-white dark:bg-gray-900">
    <div class="p-4 pt-40 sm:ml-64">
        <div class="p-1">
            <nav class="flex" aria-label="Breadcrumb">
                <ol class="inline-flex items-center space-x-1 md:space-x-2 rtl:space-x-reverse">
                    @HtmlElement.TailwindBreadCrumb(Html, items)
                </ol>
            </nav>
            <br />
            <div class="p-1">
                <div class="mt-3 grid grid-cols-12 mb-3">
                    <div class="col-span-12 lg:col-span-6">
                        <div class="bg-gray-100 dark:bg-gray-800 p-6 rounded-lg shadow-lg">
                            <h5 class="text-xl font-bold mb-4 dark:text-white">Agregar Nueva Entrada</h5>
                            <hr class="h-px my-2 bg-gray-400 border-0 dark:bg-gray-100">
                            <form action="AgregarMovEnt" method="POST" class="p-4 md:p-5">
                                <div class="grid gap-4 mb-4 grid-cols-1 md:grid-cols-3">

                                    <div class="col-span-1">
                                        <div class="block mb-2 text-md font-medium text-gray-900 dark:text-white">
                                            Monto
                                        </div>
                                        @Html.TextBoxFor(model => model.Monto, new { @class = "bg-gray-50 border border-gray-300 text-gray-900 text-md rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-800 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500", Type="number", placeholder = "Monto", required = "required" })
                                        <span asp-validation-for="Monto" class="text-red-600"></span>
                                    </div>

                                    
                                    <div class="col-span-2">
                                        <div class="block mb-2 text-md font-medium text-gray-900 dark:text-white">
                                            Comentario
                                        </div>
                                        @Html.TextBoxFor(model => model.Comentario, new { @class = "bg-gray-50 border border-gray-300 text-gray-900 text-md rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-800 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500", placeholder = "Comentario", required = "required" })
                                        <span asp-validation-for="Comentario" class="text-red-600"></span>
                                    </div>
                                </div>

                               
                                <div class="grid gap-4 mb-4 grid-cols-1 md:grid-cols-1">
                                    <div class="mt-4">
                                        @HtmlElement.Button(Html, "green", "Registrar", "", "submit", "fa-solid fa-plus", "", "")
                                        @HtmlElement.ActionLink(Html, "gray", "Regresar al listado", "IndexEnt", "Movimiento", "fa-solid fa-undo", "")
                                    </div>
                                </div>
                            </form>

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

CRM/Views/Movimiento/AgregarSal.cshtml
@using Entities.Entities
@model CRM.ViewModels.MovimientosViewModel;

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewData["Title"] = "Agregar Movimiento";
    string[] items = new string[] { "Movimientos", "Agregar Movimiento" };
}

@{

}

<div class="pt-16 lg:pl-64 pl-0 bg-white dark:bg-gray-900">
    <div class="p-4 pt-40 sm:ml-64">
        <div class="p-1">
            <nav class="flex" aria-label="Breadcrumb">
                <ol class="inline-flex items-center space-x-1 md:space-x-2 rtl:space-x-reverse">
                    @HtmlElement.TailwindBreadCrumb(Html, items)
                </ol>
            </nav>
            <br />
            <div class="p-1">
                <div class="mt-3 grid grid-cols-12 mb-3">
                    <div class="col-span-12 lg:col-span-6">
                        <div class="bg-gray-100 dark:bg-gray-800 p-6 rounded-lg shadow-lg">
                            <h5 class="text-xl font-bold mb-4 dark:text-white">Agregar Nuevo Cliente</h5>
                            <hr class="h-px my-2 bg-gray-400 border-0 dark:bg-gray-100">
                            <form action="AgregarMovSal" method="POST" class="p-4 md:p-5" enctype="multipart/form-data">

                                <div class="grid gap-4 mb-4 grid-cols-1 md:grid-cols-2">

                                    <div class="col-span-1">
                                        <div class="block mb-2 text-md font-medium text-gray-900 dark:text-white">
                                            Comentario
                                        </div>
                                        @Html.TextBoxFor(model => model.Comentario, new { @class = "bg-gray-50 border border-gray-300 text-gray-900 text-md rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-800 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500", placeholder = "Comentario", required = "required" })
                                        <span asp-validation-for="Comentario" class="text-red-600"></span>
                                    </div>
                                </div>

                                <div class="grid gap-4 mb-4 grid-cols-1 md:grid-cols-4">

                                    <div class="col-span-1">
                                        <div class="block mb-2 text-md font-medium text-gray-900 dark:text-white">
                                            Monto
                                        </div>
                                        @Html.TextBoxFor(model => model.Monto, new { @class = "bg-gray-50 border border-gray-300 text-gray-900 text-md rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-800 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500", placeholder = "Monto", required = "required" })
                                        <span asp-validation-for="Monto" class="text-red-600"></span>
                                    </div>
                                </div>

                                <div class="grid gap-4 mb-4 grid-cols-1 md:grid-cols-4">
                                    <div class="col-span-1">
                                        <div class="block mb-2 text-md font-medium text-gray-900 dark:text-white">
                                            Imagen
                                        </div>
                                        @Html.TextBoxFor(model => model.Imagen, new { type = "file", @class = "bg-gray-50 border border-gray-300 text-gray-900 text-md rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-800 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500", accept = "image/*", required = "required" })
                                        <span asp-validation-for="Imagen" class="text-red-600"></span>
                                    </div>
                                </div>


                                <div class="grid gap-4 mb-4 grid-cols-1 md:grid-cols-1">
                                    <div class="mt-4">
                                        @HtmlElement.Button(Html, "green", "Registrar", "", "submit", "fa-solid fa-plus", "", "")
                                        @HtmlElement.ActionLink(Html, "gray", "Regresar al listado", "IndexSal", "Movimiento", "fa-solid fa-undo", "")
                                    </div>
                                </div>
                            </form>

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

CRM/Views/Movimiento/EditarEnt.cshtml
@using Entities.Entities
@model CRM.ViewModels.MovimientosViewModel;

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewData["Title"] = "Editar Movimiento";
    string[] items = new string[] { "Movimientos", "Editar Movimiento" };
}

@{
    var tp = ViewData["TiposEstado"];
    IEnumerable<TipoEstadoMovimiento> tpOptions = tp as IEnumerable<TipoEstadoMovimiento>;


}

<div class="pt-16 lg:pl-64 pl-0 bg-white dark:bg-gray-900">
    <div class="p-4 pt-40 sm:ml-64">
        <div class="p-1">
            <nav class="flex" aria-label="Breadcrumb">
                <ol class="inline-flex items-center space-x-1 md:space-x-2 rtl:space-x-reverse">
                    @HtmlElement.TailwindBreadCrumb(Html, items)
                </ol>
            </nav>
            <br />
            <div class="p-1">
                <div class="mt-3 grid grid-cols-12 mb-3">
                    <div class="col-span-12 lg:col-span-6">
                        <div class="bg-gray-100 dark:bg-gray-800 p-6 rounded-lg shadow-lg">
                            <h5 class="text-xl font-bold mb-4 dark:text-white">Editar Cliente</h5>
                            <hr class="h-px my-2 bg-gray-400 border-0 dark:bg-gray-100">
                            @if (ViewData["NoItemById"] != null)
                            {
                                @HtmlElement.TailwindAlert(Html, "Advertencia", ViewData["NoItemById"].ToString(), "yellow", "fa-solid fa fa-exclamation-triangle", "")
                            }
                            @if (Model.IdMovimiento != 0)
                            {
                                <form asp-action="EditarMovEnt" class="p-4 md:p-5">
                                    <div class="grid gap-4 mb-4 grid-cols-1 md:grid-cols-2">
                                        <div hidden class="col-span-1">
                                            <div class="block mb-2 text-md font-medium text-gray-900 dark:text-white">
                                                IdCliente
                                            </div>
                                            @Html.TextBoxFor(model => model.IdMovimiento, new { @class = "bg-gray-50 border border-gray-300 text-gray-900 text-md rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-800 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" })
                                            @Html.TextBoxFor(model => model.IdUsuarioCreacion, new { @class = "bg-gray-50 border border-gray-300 text-gray-900 text-md rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-800 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" })
                                            @Html.TextBoxFor(model => model.IdUsuarioModificacion, new { @class = "bg-gray-50 border border-gray-300 text-gray-900 text-md rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-800 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" })
                                            @Html.TextBoxFor(model => model.FechaCreacion, new { @class = "bg-gray-50 border border-gray-300 text-gray-900 text-md rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-800 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" })
                                            @Html.TextBoxFor(model => model.FechaModificacion, new { @class = "bg-gray-50 border border-gray-300 text-gray-900 text-md rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-800 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" })

                                        </div>

                                        <div class="col-span-1">
                                            <div class="block mb-2 text-md font-medium text-gray-900 dark:text-white">
                                                Comentario
                                            </div>
                                            @Html.TextBoxFor(model => model.Comentario, new { @class = "bg-gray-50 border border-gray-300 text-gray-900 text-md rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-800 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500", placeholder = "Nombre del Cliente", required = "required" })
                                            <span asp-validation-for="Comentario" class="text-red-600"></span>
                                        </div>
                                    </div>

                                    <div class="grid gap-4 mb-4 grid-cols-1 md:grid-cols-4">
                                        <div class="col-span-1">
                                            <div class="block mb-2 text-md font-medium text-gray-900 dark:text-white">
                                                Monto
                                            </div>
                                            @Html.TextBoxFor(model => model.Monto, new { @class = "bg-gray-50 border border-gray-300 text-gray-900 text-md rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-800 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500", placeholder = "Correo", required = "required" })
                                            <span asp-validation-for="Monto" class="text-red-600"></span>
                                        </div>

                                        <div class="col-span-1">
                                            <div class="block mb-2 text-md font-medium text-gray-900 dark:text-white">
                                                Tipo de Estado
                                            </div>
                                            @if (tpOptions != null)
                                            {
                                                @Html.DropDownListFor(
                                                         model => model.IdEstadoMovimiento,
                                                         new SelectList(tpOptions, "IdEstadoMovimiento", "Nombre"),
                                                         "--Seleccione--",
                                                         new { @class = "bg-gray-50 border border-gray-300 text-gray-900 text-md rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-800 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500", required = "required" }
                                                         )
                                            }
                                            else
                                            {
                                                <span class="text-red-600">Debe seleccionar un tipo de identificación</span>
                                            }
                                            <span asp-validation-for="IdEstadoMovimiento" class="text-red-600"></span>
                                        </div>
                                    </div>

                                    <div class="grid gap-4 mb-4 grid-cols-1 md:grid-cols-1">
                                        <div class="mt-4">
                                            @HtmlElement.Button(Html, "blue", "Actualizar", "", "submit", "fa-solid fa-pencil", "", "")
                                            @HtmlElement.ActionLink(Html, "gray", "Regresar al listado", "IndexEnt", "Movimiento", "fa-solid fa-undo", "")
                                        </div>
                                    </div>
                                </form>

                            }

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>